In [21]:
import pandas as pd
pd.set_option("display.max_rows", None)
import pickle as pkl

2024

In [22]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[team_key["YEAR"] == 2024]

      YEAR                   TEAM  SEED  ROUND
1079  2024                  Akron    14     64
1078  2024                Alabama     4      4
1077  2024                Arizona     2     16
1076  2024                 Auburn     4     64
1075  2024                 Baylor     3     32
1073  2024                    BYU     6     64
1072  2024                Clemson     6      8
1071  2024                Colgate    14     64
1070  2024  College of Charleston    13     64
1069  2024               Colorado    10     32
1068  2024           Colorado St.    10     64
1067  2024            Connecticut     1      1
1066  2024              Creighton     3     16
1065  2024                 Dayton     7     32
1064  2024                  Drake    10     64
1063  2024                   Duke     4      8
1062  2024               Duquesne    11     32
1061  2024                Florida     7     64
1060  2024       Florida Atlantic     8     64
1059  2024                Gonzaga     5     16
1058  2024          Grambling St.    16     64
1057  2024           Grand Canyon    12     32
1056  2024                Houston     1     16
1054  2024               Illinois     3      8
1053  2024               Iowa St.     2     16
1052  2024          James Madison    12     32
1051  2024                 Kansas     4     32
1050  2024               Kentucky     3     64
1049  2024         Long Beach St.    15     64
1048  2024               Longwood    16     64
1047  2024              Marquette     2     16
1046  2024            McNeese St.    12     64
1045  2024           Michigan St.     9     32
1044  2024        Mississippi St.     8     64
1042  2024           Morehead St.    14     64
1041  2024               Nebraska     8     64
1040  2024                 Nevada    10     64
1039  2024             New Mexico    11     64
1038  2024         North Carolina     1     16
1037  2024     North Carolina St.    11      4
1036  2024           Northwestern     9     32
1035  2024                Oakland    14     32
1034  2024                 Oregon    11     32
1033  2024                 Purdue     1      2
1032  2024           Saint Mary's     5     64
1031  2024          Saint Peter's    15     64
1030  2024                Samford    13     64
1029  2024          San Diego St.     5     16
1028  2024         South Carolina     6     64
1027  2024       South Dakota St.    15     64
1026  2024                Stetson    16     64
1025  2024                    TCU     9     64
1024  2024              Tennessee     2      8
1023  2024                  Texas     7     32
1022  2024              Texas A&M     9     32
1021  2024             Texas Tech     6     64
1020  2024                    UAB    12     64
1019  2024               Utah St.     8     32
1018  2024                Vermont    13     64
1016  2024                 Wagner    16     64
1015  2024         Washington St.     7     32
1014  2024       Western Kentucky    15     64
1013  2024              Wisconsin     5     64
1012  2024                   Yale    13     32

In [23]:
test_case_2024 = [
    [
        [
            [
                [
                    [
                        1067,
                        1026
                    ],
                    [
                        1060,
                        1036
                    ]
                ],
                [
                    [
                        1029,
                        1020
                    ],
                    [
                        1076,
                        1012
                    ]
                ]
            ],
            [
                [
                    [
                        1073,
                        1062
                    ],
                    [
                        1054,
                        1042
                    ]
                ],
                [
                    [
                        1015,
                        1064
                    ],
                    [
                        1053,
                        1027
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        1038,
                        1016
                    ],
                    [
                        1044,
                        1045
                    ]
                ],
                [
                    [
                        1032,
                        1057
                    ],
                    [
                        1078,
                        1070
                    ]
                ]
            ],
            [
                [
                    [
                        1072,
                        1039
                    ],
                    [
                        1075,
                        1071
                    ]
                ],
                [
                    [
                        1065,
                        1040
                    ],
                    [
                        1077,
                        1049
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        1056,
                        1048
                    ],
                    [
                        1041,
                        1022
                    ]
                ],
                [
                    [
                        1013,
                        1052
                    ],
                    [
                        1063,
                        1018
                    ]
                ]
            ],
            [
                [
                    [
                        1021,
                        1037
                    ],
                    [
                        1050,
                        1035
                    ]
                ],
                [
                    [
                        1061,
                        1069
                    ],
                    [
                        1047,
                        1014
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        1033,
                        1058
                    ],
                    [
                        1019,
                        1025
                    ]
                ],
                [
                    [
                        1059,
                        1046
                    ],
                    [
                        1051,
                        1030
                    ]
                ]
            ],
            [
                [
                    [
                        1028,
                        1034
                    ],
                    [
                        1066,
                        1079
                    ]
                ],
                [
                    [
                        1023, 
                        1068
                    ],
                    [
                        1024,
                        1031
                    ]
                ]
            ]
        ]
    ]
]

In [24]:
with open("test_cases/test_case_2024.pkl", "wb") as f:
    pkl.dump(test_case_2024, f)

2023

In [25]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[team_key["YEAR"] == 2023]

      YEAR                    TEAM  SEED  ROUND
1011  2023                 Alabama     1     16
1010  2023                 Arizona     2     64
1009  2023             Arizona St.    11     64
1008  2023                Arkansas     8     16
1007  2023                  Auburn     9     32
1006  2023                  Baylor     3     32
1005  2023               Boise St.    10     64
1004  2023                 Colgate    15     64
1003  2023   College of Charleston    12     64
1002  2023             Connecticut     4      1
1001  2023               Creighton     6      8
1000  2023                   Drake    12     64
999   2023                    Duke     5     32
998   2023     Fairleigh Dickinson    16     32
997   2023        Florida Atlantic     9      4
996   2023                  Furman    13     32
995   2023                 Gonzaga     3      8
994   2023            Grand Canyon    14     64
993   2023                 Houston     1     16
992   2023                  Howard    16     64
991   2023                Illinois     9     64
990   2023                 Indiana     4     32
989   2023                    Iona    13     64
988   2023                    Iowa     8     64
987   2023                Iowa St.     6     64
986   2023                  Kansas     1     32
985   2023              Kansas St.     3      8
984   2023            Kennesaw St.    14     64
983   2023                Kent St.    13     64
982   2023                Kentucky     6     32
981   2023     Louisiana Lafayette    13     64
980   2023               Marquette     2     32
979   2023                Maryland     8     32
978   2023                 Memphis     8     64
977   2023                Miami FL     5      4
976   2023            Michigan St.     7     16
974   2023                Missouri     7     32
973   2023             Montana St.    14     64
971   2023      North Carolina St.    11     64
970   2023       Northern Kentucky    16     64
969   2023            Northwestern     7     32
968   2023            Oral Roberts    12     64
967   2023                Penn St.    10     32
966   2023              Pittsburgh    11     32
965   2023               Princeton    15     16
964   2023              Providence    11     64
963   2023                  Purdue     1     64
962   2023            Saint Mary's     5     32
961   2023           San Diego St.     5      2
959   2023                     TCU     6     32
958   2023               Tennessee     4     16
957   2023                   Texas     2      8
956   2023               Texas A&M     7     64
955   2023  Texas A&M Corpus Chris    16     64
953   2023        UC Santa Barbara    14     64
952   2023                    UCLA     2     16
951   2023           UNC Asheville    15     64
950   2023                     USC    10     64
949   2023                Utah St.    10     64
948   2023                     VCU    12     64
947   2023                 Vermont    15     64
946   2023                Virginia     4     64
945   2023           West Virginia     9     64
944   2023                  Xavier     3     16

In [26]:
test_case_2023 = [
    [
        [
            [
                [
                    [
                        1011,
                        955
                    ],
                    [
                        979,
                        945
                    ]
                ],
                [
                    [
                        961,
                        1003
                    ],
                    [
                        946,
                        996
                    ]
                ]
            ],
            [
                [
                    [
                        1001,
                        971
                    ],
                    [
                        1006,
                        953
                    ]
                ],
                [
                    [
                        974,
                        949
                    ],
                    [
                        1010,
                        965
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        963,
                        998
                    ],
                    [
                        978,
                        997
                    ]
                ],
                [
                    [
                        999,
                        968
                    ],
                    [
                        958,
                        981
                    ]
                ]
            ],
            [
                [
                    [
                        982,
                        964
                    ],
                    [
                        985,
                        973
                    ]
                ],
                [
                    [
                        976,
                        950
                    ],
                    [
                        980,
                        947
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        993,
                        970
                    ],
                    [
                        988,
                        1007
                    ]
                ],
                [
                    [
                        977,
                        1000
                    ],
                    [
                        990,
                        983
                    ]
                ]
            ],
            [
                [
                    [
                        987,
                        966
                    ],
                    [
                        944,
                        984
                    ]
                ],
                [
                    [
                        956,
                        967
                    ],
                    [
                        957,
                        1004
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        986,
                        992
                    ],
                    [
                        1008,
                        991
                    ]
                ],
                [
                    [
                        962,
                        948
                    ],
                    [
                        1002,
                        989
                    ]
                ]
            ],
            [
                [
                    [
                        959,
                        1009
                    ],
                    [
                        995,
                        994
                    ]
                ],
                [
                    [
                        969, 
                        1005
                    ],
                    [
                        952,
                        951
                    ]
                ]
            ]
        ]
    ]
]

In [27]:
with open("test_cases/test_case_2023.pkl", "wb") as f:
    pkl.dump(test_case_2023, f)

2022

In [28]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[team_key["YEAR"] == 2022]

     YEAR               TEAM  SEED  ROUND
943  2022              Akron    13     64
942  2022            Alabama     6     64
941  2022            Arizona     1     16
940  2022           Arkansas     4      8
939  2022             Auburn     2     32
938  2022             Baylor     1     32
937  2022          Boise St.     8     64
935  2022  Cal St. Fullerton    15     64
934  2022        Chattanooga    13     64
933  2022            Colgate    14     64
932  2022       Colorado St.     6     64
931  2022        Connecticut     5     64
930  2022          Creighton     9     32
929  2022           Davidson    10     64
928  2022           Delaware    15     64
927  2022               Duke     2      4
926  2022        Georgia St.    16     64
925  2022            Gonzaga     1     16
924  2022            Houston     5      8
923  2022           Illinois     4     32
922  2022            Indiana    12     64
921  2022               Iowa     5     64
920  2022           Iowa St.    11     16
919  2022   Jacksonville St.    15     64
918  2022             Kansas     1      1
917  2022           Kentucky     2     64
916  2022           Longwood    14     64
915  2022     Loyola Chicago    10     64
914  2022                LSU     6     64
913  2022          Marquette     9     64
912  2022            Memphis     9     32
911  2022           Miami FL    10      8
910  2022           Michigan    11     16
909  2022       Michigan St.     7     32
908  2022        Montana St.    14     64
907  2022         Murray St.     7     32
906  2022     New Mexico St.    12     32
905  2022        Norfolk St.    16     64
904  2022     North Carolina     8      2
903  2022         Notre Dame    11     32
902  2022           Ohio St.     7     32
901  2022         Providence     4     16
900  2022             Purdue     3     16
899  2022           Richmond    12     32
897  2022       Saint Mary's     5     32
896  2022      Saint Peter's    15      8
895  2022      San Diego St.     8     64
894  2022      San Francisco    10     64
893  2022         Seton Hall     8     64
892  2022   South Dakota St.    13     64
891  2022                TCU     9     32
890  2022          Tennessee     3     32
889  2022              Texas     6     32
887  2022     Texas Southern    16     64
886  2022         Texas Tech     3     16
885  2022                UAB    12     64
884  2022               UCLA     4     16
883  2022                USC     7     64
882  2022            Vermont    13     64
881  2022          Villanova     2      4
880  2022      Virginia Tech    11     64
879  2022          Wisconsin     3     32
878  2022         Wright St.    16     64
876  2022               Yale    14     64

In [29]:
test_case_2022 = [
    [
        [
            [
                [
                    [
                        925,
                        926
                    ],
                    [
                        937,
                        912
                    ]
                ],
                [
                    [
                        931,
                        906
                    ],
                    [
                        940,
                        882
                    ]
                ]
            ],
            [
                [
                    [
                        942,
                        903
                    ],
                    [
                        886,
                        908
                    ]
                ],
                [
                    [
                        909,
                        929
                    ],
                    [
                        927,
                        935
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        938,
                        905
                    ],
                    [
                        904,
                        913
                    ]
                ],
                [
                    [
                        897,
                        922
                    ],
                    [
                        884,
                        943
                    ]
                ]
            ],
            [
                [
                    [
                        889,
                        880
                    ],
                    [
                        900,
                        876
                    ]
                ],
                [
                    [
                        907,
                        894
                    ],
                    [
                        917,
                        896
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        941,
                        878
                    ],
                    [
                        893,
                        891
                    ]
                ],
                [
                    [
                        924,
                        885
                    ],
                    [
                        923,
                        934
                    ]
                ]
            ],
            [
                [
                    [
                        932,
                        910
                    ],
                    [
                        890,
                        916
                    ]
                ],
                [
                    [
                        902,
                        915
                    ],
                    [
                        881,
                        928
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        918,
                        887
                    ],
                    [
                        895,
                        930
                    ]
                ],
                [
                    [
                        921,
                        899
                    ],
                    [
                        901,
                        892
                    ]
                ]
            ],
            [
                [
                    [
                        914,
                        920
                    ],
                    [
                        879,
                        933
                    ]
                ],
                [
                    [
                        883, 
                        911
                    ],
                    [
                        939,
                        919
                    ]
                ]
            ]
        ]
    ]
]

In [30]:
with open("test_cases/test_case_2022.pkl", "wb") as f:
    pkl.dump(test_case_2022, f)

In [31]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[team_key["YEAR"] == 2021]

     YEAR                TEAM  SEED  ROUND
875  2021   Abilene Christian    14     32
874  2021             Alabama     2     16
872  2021            Arkansas     3      8
871  2021              Baylor     1      1
870  2021                 BYU     6     64
869  2021             Clemson     7     64
868  2021       Cleveland St.    15     64
867  2021             Colgate    14     64
866  2021            Colorado     5     32
865  2021         Connecticut     7     64
864  2021           Creighton     5     16
863  2021               Drake    11     64
862  2021              Drexel    16     64
861  2021  Eastern Washington    14     64
860  2021             Florida     7     32
859  2021         Florida St.     4     16
858  2021          Georgetown    12     64
857  2021        Georgia Tech     9     64
856  2021             Gonzaga     1      2
855  2021        Grand Canyon    15     64
854  2021            Hartford    16     64
853  2021             Houston     2      4
852  2021            Illinois     1     32
851  2021                Iona    15     64
850  2021                Iowa     2     32
849  2021              Kansas     3     32
848  2021             Liberty    13     64
847  2021      Loyola Chicago     8     16
846  2021                 LSU     8     32
845  2021            Maryland    10     32
844  2021            Michigan     1      8
842  2021            Missouri     9     64
841  2021        Morehead St.    14     64
839  2021         Norfolk St.    16     64
838  2021      North Carolina     8     64
837  2021         North Texas    13     32
836  2021                Ohio    13     32
835  2021            Ohio St.     2     64
834  2021            Oklahoma     8     32
833  2021        Oklahoma St.     4     32
832  2021        Oral Roberts    15     16
831  2021              Oregon     7     16
830  2021          Oregon St.    12      8
829  2021              Purdue     4     64
828  2021             Rutgers    10     32
827  2021       San Diego St.     6     64
826  2021     St. Bonaventure     9     64
825  2021            Syracuse    11     16
824  2021           Tennessee     5     64
823  2021               Texas     3     64
822  2021      Texas Southern    16     64
821  2021          Texas Tech     6     32
820  2021    UC Santa Barbara    12     64
819  2021                UCLA    11      4
818  2021      UNC Greensboro    13     64
817  2021                 USC     6      8
816  2021            Utah St.    11     64
815  2021                 VCU    10     64
814  2021           Villanova     5     16
813  2021            Virginia     4     64
812  2021       Virginia Tech    10     64
811  2021       West Virginia     3     32
809  2021            Winthrop    12     64
808  2021           Wisconsin     9     32

In [32]:
test_case_2021 = [
    [
        [
            [
                [
                    [
                        856,
                        839
                    ],
                    [
                        834,
                        842
                    ]
                ],
                [
                    [
                        864,
                        820
                    ],
                    [
                        813,
                        836
                    ]
                ]
            ],
            [
                [
                    [
                        817,
                        863
                    ],
                    [
                        849,
                        861
                    ]
                ],
                [
                    [
                        831,
                        815
                    ],
                    [
                        850,
                        855
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        844,
                        822
                    ],
                    [
                        846,
                        826
                    ]
                ],
                [
                    [
                        866,
                        858
                    ],
                    [
                        859,
                        818
                    ]
                ]
            ],
            [
                [
                    [
                        870,
                        819
                    ],
                    [
                        823,
                        875
                    ]
                ],
                [
                    [
                        865,
                        845
                    ],
                    [
                        874,
                        851
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        871,
                        854
                    ],
                    [
                        838,
                        808
                    ]
                ],
                [
                    [
                        814,
                        809
                    ],
                    [
                        829,
                        837
                    ]
                ]
            ],
            [
                [
                    [
                        821,
                        816
                    ],
                    [
                        872,
                        867
                    ]
                ],
                [
                    [
                        860,
                        812
                    ],
                    [
                        835,
                        832
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        852,
                        862
                    ],
                    [
                        847,
                        857
                    ]
                ],
                [
                    [
                        824,
                        830
                    ],
                    [
                        833,
                        848
                    ]
                ]
            ],
            [
                [
                    [
                        827,
                        825
                    ],
                    [
                        811,
                        841
                    ]
                ],
                [
                    [
                        869, 
                        828
                    ],
                    [
                        853,
                        868
                    ]
                ]
            ]
        ]
    ]
]

In [33]:
with open("test_cases/test_case_2021.pkl", "wb") as f:
    pkl.dump(test_case_2021, f)

In [34]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[team_key["YEAR"] == 2025]

      YEAR              TEAM  SEED  ROUND
1147  2025             Akron    13     64
1146  2025           Alabama     2      0
1145  2025       Alabama St.    16     64
1143  2025           Arizona     4      0
1142  2025          Arkansas    10      0
1141  2025            Auburn     1      0
1140  2025            Baylor     9     32
1139  2025            Bryant    15     64
1138  2025               BYU     6      0
1137  2025           Clemson     5     64
1136  2025      Colorado St.    12     32
1135  2025       Connecticut     8     32
1134  2025         Creighton     9     32
1133  2025             Drake    11     32
1132  2025              Duke     1      0
1131  2025           Florida     1      0
1130  2025           Georgia     9     64
1129  2025           Gonzaga     8     32
1128  2025      Grand Canyon    13     64
1127  2025        High Point    13     64
1126  2025           Houston     1      0
1125  2025          Illinois     6     32
1124  2025          Iowa St.     3     32
1123  2025            Kansas     7     64
1122  2025          Kentucky     3      0
1121  2025           Liberty    12     64
1120  2025          Lipscomb    14     64
1119  2025        Louisville     8     64
1118  2025         Marquette     7     64
1117  2025          Maryland     4      0
1116  2025       McNeese St.    12     32
1115  2025           Memphis     5     64
1114  2025          Michigan     5      0
1113  2025      Michigan St.     2      0
1112  2025       Mississippi     6      0
1111  2025   Mississippi St.     8     64
1110  2025          Missouri     6     64
1109  2025           Montana    14     64
1108  2025  Mount St. Mary's    16     64
1107  2025    Nebraska Omaha    15     64
1106  2025        New Mexico    10     32
1105  2025       Norfolk St.    16     64
1104  2025    North Carolina    11     64
1103  2025          Oklahoma     9     64
1102  2025            Oregon     5     32
1101  2025            Purdue     4      0
1100  2025     Robert Morris    15     64
1098  2025      Saint Mary's     7     32
1096  2025  SIU Edwardsville    16     64
1095  2025        St. John's     2     32
1094  2025         Tennessee     2      0
1092  2025         Texas A&M     4     32
1091  2025        Texas Tech     3      0
1090  2025              Troy    14     64
1089  2025      UC San Diego    12     64
1088  2025              UCLA     7     32
1087  2025    UNC Wilmington    14     64
1086  2025          Utah St.    10     64
1085  2025        Vanderbilt    10     64
1084  2025               VCU    11     64
1083  2025         Wisconsin     3     32
1082  2025           Wofford    15     64
1081  2025            Xavier    11     64
1080  2025              Yale    13     64

In [35]:
test_case_2025 = [
    [
        [
            [
                [
                    [
                        1141,
                        1145
                    ],
                    [
                        1119,
                        1134
                    ]
                ],
                [
                    [
                        1114,
                        1089
                    ],
                    [
                        1092,
                        1080
                    ]
                ]
            ],
            [
                [
                    [
                        1112,
                        1104
                    ],
                    [
                        1124,
                        1120
                    ]
                ],
                [
                    [
                        1118,
                        1106
                    ],
                    [
                        1113,
                        1139
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        1131,
                        1105
                    ],
                    [
                        1135,
                        1103
                    ]
                ],
                [
                    [
                        1115,
                        1136
                    ],
                    [
                        1117,
                        1128
                    ]
                ]
            ],
            [
                [
                    [
                        1110,
                        1133
                    ],
                    [
                        1091,
                        1087
                    ]
                ],
                [
                    [
                        1123,
                        1142
                    ],
                    [
                        1095,
                        1107
                    ]
                ]
            ]
        ]
    ],
    [
        [
            [
                [
                    [
                        1132,
                        1108
                    ],
                    [
                        1111,
                        1140
                    ]
                ],
                [
                    [
                        1102,
                        1121
                    ],
                    [
                        1143,
                        1147
                    ]
                ]
            ],
            [
                [
                    [
                        1138,
                        1084
                    ],
                    [
                        1083,
                        1109
                    ]
                ],
                [
                    [
                        1098,
                        1085
                    ],
                    [
                        1146,
                        1100
                    ]
                ]
            ]
        ],
        [
            [
                [
                    [
                        1126,
                        1096
                    ],
                    [
                        1129,
                        1130
                    ]
                ],
                [
                    [
                        1137,
                        1116
                    ],
                    [
                        1101,
                        1127
                    ]
                ]
            ],
            [
                [
                    [
                        1125,
                        1081
                    ],
                    [
                        1122,
                        1090
                    ]
                ],
                [
                    [
                        1088, 
                        1086
                    ],
                    [
                        1094,
                        1082
                    ]
                ]
            ]
        ]
    ]
]

In [36]:
with open("test_cases/test_case_2025.pkl", "wb") as f:
    pkl.dump(test_case_2025, f)

In [37]:
team_key = pd.read_csv("processed_data/team_key.csv", index_col = 0)
team_key.loc[(team_key["YEAR"] == 2025) & (team_key["ROUND"] < 32)]

      YEAR          TEAM  SEED  ROUND
1146  2025       Alabama     2      0
1143  2025       Arizona     4      0
1142  2025      Arkansas    10      0
1141  2025        Auburn     1      0
1138  2025           BYU     6      0
1132  2025          Duke     1      0
1131  2025       Florida     1      0
1126  2025       Houston     1      0
1122  2025      Kentucky     3      0
1117  2025      Maryland     4      0
1114  2025      Michigan     5      0
1113  2025  Michigan St.     2      0
1112  2025   Mississippi     6      0
1101  2025        Purdue     4      0
1094  2025     Tennessee     2      0
1091  2025    Texas Tech     3      0

In [38]:
test_case_S16_2025 = [
    [
        [
            [
                1141,
                1114
            ],
            [
                1112,
                1113
            ]
        ],
        [
            [
                1131,
                1117
            ],
            [
                1091,
                1142
            ]
        ]
    ],
    [
        [
            [
                1132,
                1143
            ],
            [
                1138,
                1146
            ]
        ],
        [
            [
                1126,
                1101
            ],
            [
                1122,
                1094
            ]
        ]
    ]
]

In [39]:
with open("test_cases/test_case_S16_2025.pkl", "wb") as f:
    pkl.dump(test_case_S16_2025, f)